#!/bin/bash

# Function to display help message
function help() {
    echo "Usage: install [option]"
    echo "Options:"
    echo "  list"
    echo "  all"
    echo "  ide"
    echo "  langs"
    echo "  gui"
    echo "  gnome"
}

# Function to handle the 'list' argument
function list() {
    echo "Installer options:"
    echo "  all (ide and langs)"
    echo "  ide"
    echo "  langs"
    echo "  gui"
    echo "  gnome"
}

function all() {
    ide
    langs
}

function ide() {
    ./installers/ide
}

function langs() {
    ./installers/langs
}

function gui() {
    ./installers/gui
}

function gnome() {
    ./installers/gnome
}

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "No arguments provided. Use 'help' for usage information."
    exit 1
fi

# make all scripts executable
chmod +x installers/*

# Parse the argument
case $1 in
list) list ;;
help) help ;;
all) all ;;
ide) ide ;;
langs) langs ;;
gui) gui ;;
gnome) gnome ;;
*)
    echo "Invalid option: $1"
    help
    exit 1
    ;;
esac
