#!/bin/bash

ide=(
    git
    stow
    man-db
    htop
    curl
    wget
    openssh

    fd
    ripgrep
    neofetch

    zsh
    oh-my-zsh-git
    zsh-autocomplete-git
    zsh-autosuggestions-git
    zsh-syntax-highlighting-git
    zsh-fast-syntax-highlighting-git

    tmux
    starship
    zoxide
    eza
    lazygit

    neovim
)

# raw install
./installers/yeah "${ide[@]}"
./installers/stow "${ide[@]}"

# set shell
if ! $(cat /etc/passwd | grep -q zsh); then
    chsh -s /usr/bin/zsh "$USER"
fi
