#!/bin/bash

yay -Sy --needed --noconfirm kanata
stow --target="$HOME" .
sudo cp kanata.service /usr/lib/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable kanata.service
sudo systemctl start kanata.service
